### PR TITLE
flightaware updates

### PR DESCRIPTION
**Pull request by twpayne**
Hey @polastre, wanna open a PR with all your improvements?

### CODE REVIEW

**Comment by polastre** [comment]
There’s a few more changes I want to make to optimize tile generation and document some stuff in the README, then I’d be happy to mark this PR ready for review.

**Comment by twpayne** [comment]
Cool, thanks!

**Comment by polastre** [comment]
@twpayne this is ready, can you update this PR with the latest commits from the remote branch?

**Comment by twpayne** [comment]
Thanks @polastre! Would you be able to create a PR with the changes? This will ensure that you get proper credit for your work in the repo commit history and on GitHub.

**Comment by polastre** [comment]
I think because you opened this PR, it won't let me open my own PR from my branch

**Comment by twpayne** [comment]
OK, I'll close this now.

**Pull request closed without merging**
